/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package read.with.us;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class borrowBook extends javax.swing.JFrame {

    /**
     * Creates new form borrowBook
     */
    public borrowBook() {
        initComponents();
        checkAnotherBK();
        
    }
    
    void checkAnotherBK() //Check whether user needs another book to borrow
    {
       
            bkid2.setVisible(false);
            bkname2.setVisible(false);
            bkid_lable1.setVisible(false);
            bkname_lable2.setVisible(false);
            searchid2.setVisible(false);
            
           
        
         
      
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        jPanel1 = new javax.swing.JPanel();
        stdID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        borrowID = new javax.swing.JTextField();
        memName = new javax.swing.JTextField();
        bkid1 = new javax.swing.JTextField();
        bkname1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bkid_lable1 = new javax.swing.JLabel();
        bkname_lable2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        searchid2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        bkname2 = new javax.swing.JTextField();
        bkid2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        add = new javax.swing.JButton();
        add_check = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jButton7 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setLayout(null);

        stdID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdIDActionPerformed(evt);
            }
        });
        jPanel1.add(stdID);
        stdID.setBounds(230, 40, 135, 33);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("M:\\Icons\\Actions-user-group-new-icon.png")); // NOI18N
        jLabel1.setText("Member ID");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, 40, 110, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("M:\\Icons\\search_24px_29037_easyicon.net.png")); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(380, 40, 101, 33);
        jPanel1.add(borrowID);
        borrowID.setBounds(130, 110, 126, 28);
        jPanel1.add(memName);
        memName.setBounds(130, 150, 126, 28);
        jPanel1.add(bkid1);
        bkid1.setBounds(130, 210, 126, 28);

        bkname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkname1ActionPerformed(evt);
            }
        });
        jPanel1.add(bkname1);
        bkname1.setBounds(130, 250, 126, 28);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Borrow ID");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 120, 80, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Member Name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 160, 100, 15);

        bkid_lable1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bkid_lable1.setForeground(new java.awt.Color(255, 255, 0));
        bkid_lable1.setText("Book ID");
        jPanel1.add(bkid_lable1);
        bkid_lable1.setBounds(400, 220, 60, 15);

        bkname_lable2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bkname_lable2.setForeground(new java.awt.Color(255, 255, 0));
        bkname_lable2.setText("Book Name");
        jPanel1.add(bkname_lable2);
        bkname_lable2.setBounds(390, 260, 80, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("End Date");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(60, 340, 80, 15);

        searchid2.setIcon(new javax.swing.ImageIcon("M:\\Icons\\search_24px_29037_easyicon.net.png")); // NOI18N
        searchid2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchid2ActionPerformed(evt);
            }
        });
        jPanel1.add(searchid2);
        searchid2.setBounds(610, 210, 30, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon("M:\\Icons\\ok-2-icon.png")); // NOI18N
        jButton3.setText("ISSUE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(130, 380, 120, 30);
        jPanel1.add(bkname2);
        bkname2.setBounds(470, 250, 130, 30);
        jPanel1.add(bkid2);
        bkid2.setBounds(470, 210, 130, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("Book ID");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(60, 220, 60, 15);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 0));
        jLabel9.setText("Book Name");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(50, 260, 80, 15);

        jButton4.setIcon(new javax.swing.ImageIcon("M:\\Icons\\search_24px_29037_easyicon.net.png")); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(260, 210, 30, 30);

        add.setIcon(new javax.swing.ImageIcon("M:\\Icons\\Actions-list-add-icon.png")); // NOI18N
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add);
        add.setBounds(320, 280, 40, 40);

        add_check.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        add_check.setForeground(new java.awt.Color(255, 255, 255));
        add_check.setText("ADD");
        add_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_checkActionPerformed(evt);
            }
        });
        jPanel1.add(add_check);
        add_check.setBounds(320, 330, 60, 23);

        jButton2.setIcon(new javax.swing.ImageIcon("M:\\Icons\\Actions-edit-undo-icon.png")); // NOI18N
        jButton2.setToolTipText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(580, 330, 50, 40);

        jButton5.setIcon(new javax.swing.ImageIcon("M:\\Icons\\arrow-back-icon.png")); // NOI18N
        jButton5.setToolTipText("Go Back");
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(520, 330, 50, 40);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon("M:\\Icons\\Favorities-icon.png")); // NOI18N
        jButton6.setText("View ");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(399, 330, 110, 40);
        jPanel1.add(jDateChooser1);
        jDateChooser1.setBounds(130, 290, 130, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 0));
        jLabel10.setText("Issue Date");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(50, 300, 80, 15);
        jPanel1.add(jDateChooser2);
        jDateChooser2.setBounds(130, 330, 130, 30);

        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(270, 330, 30, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon("M:\\Assignments\\3rd Assignments\\JAVA\\Images\\logo3.png")); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(550, 0, 100, 80);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon("M:\\Icons\\ssa.png")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(-10, 0, 660, 470);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bkname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bkname1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Connection con = null;
        ResultSet rs;
        String id = stdID.getText();
        try {
            con= DriverManager.getConnection("jdbc:mysql://localhost/library", "root", "");
          
        } catch (SQLException ex) {
            Logger.getLogger(Memeber.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
          PreparedStatement ps = con.prepareStatement("select * from mem where id=?");
          ps.setString(1, id);
           rs = ps.executeQuery();
           while(rs.next())
           {
               memName.setText(rs.getString(3));
           }
        
         }
         catch (SQLException ex) {
            Logger.getLogger(Memeber.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally
        {
            try {
                con.close();
            } catch (SQLException ex) {
                Logger.getLogger(borrowBook.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        Connection con = null;
        ResultSet rs;
        String id = bkid1.getText();
        try {
            con= DriverManager.getConnection("jdbc:mysql://localhost/library", "root", "");
          
        } catch (SQLException ex) {
            Logger.getLogger(Memeber.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
          PreparedStatement ps = con.prepareStatement("select * from book where id=?");
          ps.setString(1, id);
           rs = ps.executeQuery();
          
           while(rs.next())
           {
               bkname1.setText(rs.getString(3));
           }   
        
         }
         catch (SQLException ex) {
            Logger.getLogger(Memeber.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally
        {
            try {
                con.close();
            } catch (SQLException ex) {
                Logger.getLogger(borrowBook.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        Connection con = null;
        try {
            con= DriverManager.getConnection("jdbc:mysql://localhost/library", "root", "");
           
          
        } catch (SQLException ex) {
            Logger.getLogger(Memeber.class.getName()).log(Level.SEVERE, null, ex);
           
        }
       
        if(add_check.isSelected())
        {
            try {
           PreparedStatement ps = con.prepareStatement("INSERT INTO borrowbk(borrowID,memID,memName,bk_id,bk_name,issue_date,end_date,bk_name_2,bk_id_2) values(?,?,?,?,?,?,?,?,?)");
           ps.setInt(1, Integer.parseInt(borrowID.getText()));
           ps.setInt(2, Integer.parseInt(stdID.getText()));
           ps.setString(3,memName.getText());
           ps.setInt(4,Integer.parseInt(bkid1.getText()));
           ps.setString(5,bkname1.getText());
           
           SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());
           String issuedate = sdf.format(jDateChooser1.getDate());
           ps.setString(6, issuedate);
           
           
           String enddate = sdf.format(jDateChooser2.getDate());
           ps.setString(7, enddate);
          

           
           ps.setString(8, bkname2.getText());
           ps.setInt(9, Integer.parseInt(bkid2.getText()));
           ps.execute();
           ImageIcon icon = new ImageIcon("M:\\Icons/success-icon.png"); 
            JOptionPane.showMessageDialog(null, " Data Successfully Inserted !","Success",JOptionPane.PLAIN_MESSAGE,icon);
            borrowID.setText("");
stdID.setText("");
memName.setText("");
bkid1.setText("");
bkname1.setText("");

            
            
        } catch (SQLException ex) {
            Logger.getLogger(borrowBook.class.getName()).log(Level.SEVERE, null, ex);
        }

        }
        else
        {
             //Connection String
        try {
           PreparedStatement ps = con.prepareStatement("INSERT INTO borrowbk(borrowID,memID,memName,bk_id,bk_name,issue_date,end_date,bk_name_2,bk_id_2) values(?,?,?,?,?,?,?,?,?)");
           ps.setInt(1, Integer.parseInt(borrowID.getText()));
           ps.setInt(2, Integer.parseInt(stdID.getText()));
           ps.setString(3,memName.getText());
           ps.setInt(4,Integer.parseInt(bkid1.getText()));
           ps.setString(5,bkname1.getText());
           SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());
           String issuedate = sdf.format(jDateChooser1.getDate());
           ps.setString(6, issuedate);
           
           String enddate = sdf.format(jDateChooser2.getDate());
           ps.setString(7, enddate);
           
           
           
           ps.setString(8, "None");
           ps.setInt(9, 0);
           ps.execute();
           ImageIcon icon = new ImageIcon("M:\\Icons/success-icon.png"); 
            JOptionPane.showMessageDialog(null, " Data Successfully Inserted !","Success",JOptionPane.PLAIN_MESSAGE,icon);
            
borrowID.setText("");
stdID.setText("");
memName.setText("");
bkid1.setText("");
bkname1.setText("");
bkid2.setText("");
bkname2.setText("");
            
        } catch (SQLException ex) {
            Logger.getLogger(borrowBook.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:

        bkid2.setVisible(true);
        bkname2.setVisible(true);
        bkid_lable1.setVisible(true);
        bkname_lable2.setVisible(true);
        searchid2.setVisible(true);
        add_check.setSelected(true);
    }//GEN-LAST:event_addActionPerformed

    private void searchid2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchid2ActionPerformed
        // TODO add your handling code here:

        Connection con = null;
        ResultSet rs;
        String id = bkid2.getText();
        try {
            con= DriverManager.getConnection("jdbc:mysql://localhost/library", "root", "");

        } catch (SQLException ex) {
            Logger.getLogger(Memeber.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            PreparedStatement ps = con.prepareStatement("select * from book where id=?");
            ps.setString(1, id);
            rs = ps.executeQuery();
            while(rs.next())
            {
                bkname2.setText(rs.getString(3));
            }

        }
        catch (SQLException ex) {
            Logger.getLogger(Memeber.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally
        {
            try {
                con.close();
            } catch (SQLException ex) {
                Logger.getLogger(borrowBook.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_searchid2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here
borrowID.setText("");
stdID.setText("");
memName.setText("");
bkid1.setText("");
bkname1.setText("");
bkid2.setText("");
bkname2.setText("");

bkid2.setVisible(false);
        bkname2.setVisible(false);
        bkid_lable1.setVisible(false);
        bkname_lable2.setVisible(false);
        searchid2.setVisible(false);
        add_check.setSelected(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void stdIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stdIDActionPerformed

    private void add_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_checkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_checkActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Books bk = new Books();
        bk.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        viewBorrowBK bk = new viewBorrowBK();
        bk.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());   
Calendar c = Calendar.getInstance();
c.setTime(jDateChooser1.getDate()); // 
c.add(Calendar.DATE, 14); // Adding 14 days
jDateChooser2.setDate(c.getTime());
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(borrowBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(borrowBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(borrowBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(borrowBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new borrowBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JCheckBox add_check;
    private javax.swing.JTextField bkid1;
    private javax.swing.JTextField bkid2;
    private javax.swing.JLabel bkid_lable1;
    private javax.swing.JTextField bkname1;
    private javax.swing.JTextField bkname2;
    private javax.swing.JLabel bkname_lable2;
    private javax.swing.JTextField borrowID;
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField memName;
    private javax.swing.JButton searchid2;
    private javax.swing.JTextField stdID;
    // End of variables declaration//GEN-END:variables
}
