/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package read.with.us;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class viewBorrowBK extends javax.swing.JFrame {

    /**
     * Creates new form viewBorrowBK
     */
    public viewBorrowBK() {
        initComponents();
        display();
    }
     void display() // Display Member Details in separate Panel
    {
       
        Connection con = null;
        try {
            con= DriverManager.getConnection("jdbc:mysql://localhost/library", "root", "");
           
          
        } catch (SQLException ex) {
            Logger.getLogger(Memeber.class.getName()).log(Level.SEVERE, null, ex);
           
        }
        
        try {
            PreparedStatement st = con.prepareStatement("select * from borrowbk");
            ResultSet rs = st.executeQuery();
            DefaultTableModel tb = (DefaultTableModel)borrowBKList.getModel();
            tb.setRowCount(0);
            
            while(rs.next())
            {
                Object o[] = {rs.getInt("borrowID"),rs.getInt("memID"),rs.getString("memName"),rs.getString("bk_id"),rs.getString("bk_name"),rs.getDate("issue_date"),rs.getString("bk_id_2"),rs.getString("bk_name_2"),rs.getDate("end_date")};
               tb.addRow(o);
                
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(Memeber.class.getName()).log(Level.SEVERE, null, ex);
        }
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        borrowBKList = new javax.swing.JTable();
        search = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        borrowBKList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Borrow Id", "Member Id", "Member Nam", "Book Id", "Book Nam", "Issue Date", "2nd Book Id", "2nd Book Nam", "End Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        borrowBKList.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(borrowBKList);
        if (borrowBKList.getColumnModel().getColumnCount() > 0) {
            borrowBKList.getColumnModel().getColumn(0).setResizable(false);
            borrowBKList.getColumnModel().getColumn(1).setResizable(false);
            borrowBKList.getColumnModel().getColumn(2).setResizable(false);
            borrowBKList.getColumnModel().getColumn(3).setResizable(false);
            borrowBKList.getColumnModel().getColumn(4).setResizable(false);
            borrowBKList.getColumnModel().getColumn(5).setResizable(false);
            borrowBKList.getColumnModel().getColumn(6).setResizable(false);
            borrowBKList.getColumnModel().getColumn(7).setResizable(false);
            borrowBKList.getColumnModel().getColumn(8).setResizable(false);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 90, 630, 280);
        jPanel1.add(search);
        search.setBounds(400, 30, 120, 30);

        jButton1.setIcon(new javax.swing.ImageIcon("M:\\Icons\\Search-icon.png")); // NOI18N
        jButton1.setToolTipText("Search By ID");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(530, 30, 40, 40);

        jButton2.setIcon(new javax.swing.ImageIcon("M:\\Icons\\arrow-back-icon.png")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(590, 380, 50, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon("M:\\Icons\\Mayor-Book-icon (2).png")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 10, 110, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon("M:\\Icons\\stylish-background-dark-shade-134814.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 650, 430);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Connection con = null;
            try {
            con= DriverManager.getConnection("jdbc:mysql://localhost/library", "root", "");
           
          
        } catch (SQLException ex) {
            Logger.getLogger(Memeber.class.getName()).log(Level.SEVERE, null, ex);
           
        }
             try {
            PreparedStatement st = con.prepareStatement("select * from borrowbk where borrowID=?");
            st.setInt(1, Integer.parseInt(search.getText()));
            ResultSet rs = st.executeQuery();
            DefaultTableModel tb = (DefaultTableModel)borrowBKList.getModel();
            tb.setRowCount(0);
            
            while(rs.next())
            {
               Object o[] = {rs.getInt("borrowID"),rs.getInt("memID"),rs.getString("memName"),rs.getString("bk_id"),rs.getString("bk_name"),rs.getDate("issue_date"),
                   rs.getString("bk_id_2"),rs.getString("bk_name_2"),rs.getDate("end_date")};
               tb.addRow(o);
                
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(Memeber.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        borrowBook bk = new borrowBook();
        bk.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewBorrowBK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewBorrowBK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewBorrowBK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewBorrowBK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewBorrowBK().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable borrowBKList;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField search;
    // End of variables declaration//GEN-END:variables
}
